### ISSUE TITLE
MongoDB url

### ISSUE THREAD

**Issue by thewolf87** [Asthriona/Yukiko#17]
Please help me I don't know how to get mongodb url like `mongodb://yukiko:127.0.0.1` I have free MongoDB atlas

**Comment by Asthriona** [comment]
Sure, did you already setup your cluster?
then just click "connect" copy the "link", replace `mongodb://yukiko:127.0.0.1` by the URI you got on Mongo Atlas.

as example:
``` 
"dbLink": "mongodb+srv://USERNAME:PASSWORD@yukiko.mongodb.net/discordbot?retryWrites=true&w=majority"
```

I hope it help! :)

**Comment by thewolf87** [comment]
Thanks but I have `mongodb+srv://USERNAME: PASSWORD@hard69-zbz51.mongodb.net/test?retryWrites=true&w=majority` but how do I convert it into `mongodb://yukiko:127.0.0.1`

**Comment by Asthriona** [comment]
No you dont have to covert anything, just replace the example one.  so for you it should look like:
```
"dbLink": "mongodb+srv://USERNAME:PASSWORD@hard69-zbz51.mongodb.net/test?retryWrites=true&w=majority"
```

**Comment by thewolf87** [comment]
I tried but it says `ERROR Unable to connect to the Mongodb database. Error:MongooseServerSelectionError: connection <monitor> to 3.6.213.55:27017 closed `

**Comment by Asthriona** [comment]
can you post the full logs and the mongoose connection code part please?

**Comment by Asthriona** [comment]
Oh, nvm.... I forgot this was an option... @thewolf87 Did you add your IP to the whitelist (IP of your home AND server?) if not try it, in Network Access on Mongo Atlas.

**Comment by thewolf87** [comment]
I just checked that there is an ip in network access but I didn't added it so what do I have to do with that ip?

**Comment by Asthriona** [comment]
@thewolf87, Just add your IP to the whitelist.
You probably have a dynamic IP. so if you host the bot behind your box you will have to update that IP every day OR allow connection from anyway. but adding your IP should fix your error.

**Comment by Heazher** [comment]
After one week without reply, i'm closing this issue. Feel free to re-open or create a new one if needed.
