### ISSUE TITLE
Cant run the bot when i type help

### ISSUE THREAD

**Issue by itsmarti123** [Asthriona/Yukiko#236]
YukikoDB: Can not connect Error: MongooseServerSelectionError: getaddrinfo ENOTFOUND yukiko
C:\Users\Admin\Downloads\Yukiko-master\Yukiko-master\index.js:24
    bot.commands = new discord.Collection();
                 ^

TypeError: Cannot set property 'commands' of undefined
    at NativeConnection.<anonymous> (C:\Users\Admin\Downloads\Yukiko-master\Yukiko-master\index.js:24:18)
    at NativeConnection.emit (events.js:315:20)
    at C:\Users\Admin\Downloads\Yukiko-master\Yukiko-master\node_modules\mongoose\lib\connection.js:841:37
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yukiko@2.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yukiko@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2021-02-03T11_08_06_073Z-debug.log

**Comment by Asthriona** [comment]
hi! 
I would like to ask you few question just to make sure its not a user error, but just know I'm currently trying to reproduce your issue on my machine.

What do you mean exactly by `Cant run the bot when i type help` ?
is there any error on start?
did you modify the code?
Edit: I forgot a question.  What branch are you using?

Thank you.

**Comment by itsmarti123** [comment]
20:56:15:487 -- 02/03/2021 -> Latin Clan -> LatinCrocodile: l!help
MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous>
(C:\Users\Admin\Downloads\Yukiko-master\Yukiko-master\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
MongooseError: Operation `cards.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous>
(C:\Users\Admin\Downloads\Yukiko-master\Yukiko-master\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
YukikoDB: Can not connect Error: MongooseServerSelectionError: getaddrinfo
ENOTFOUND yukiko
C:\Users\Admin\Downloads\Yukiko-master\Yukiko-master\index.js:24
    bot.commands = new discord.Collection();
                 ^

TypeError: Cannot set property 'commands' of undefined
    at NativeConnection.<anonymous>
(C:\Users\Admin\Downloads\Yukiko-master\Yukiko-master\index.js:24:18)
    at NativeConnection.emit (events.js:315:20)
    at
C:\Users\Admin\Downloads\Yukiko-master\Yukiko-master\node_modules\mongoose\lib\connection.js:854:37
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Noong Miy, Peb 3, 2021 nang 7:19 PM, sinulat ni Asthriona <
notifications@github.com> ang:

**Comment by Asthriona** [comment]
Thats much more uselfull logs.
Your issue is the database. 
```
MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous>
```
Please make sure your MongoDB is configured and you get the `YukikoDB Connecte` message. 
if you dont know how to setup mongoDB please read the [README.md](https://github.com/Asthriona/Yukiko#configuration)

**Comment by itsmarti123** [comment]
thank u c'ya!

Noong Miy, Peb 3, 2021 nang 9:01 PM, sinulat ni Asthriona <
notifications@github.com> ang:

**Comment by itsmarti123** [comment]
how do i do it cuz in the video u r using other website?

Noong Miy, Peb 3, 2021 nang 9:06 PM, sinulat ni Its Marti <
itsmarti095@gmail.com> ang:

**Comment by Asthriona** [comment]
you are very welcome :)
