### ISSUE TITLE
error with code

### ISSUE THREAD

**Issue by FirezTheGreat** [Asthriona/Yukiko#25]
https://github.com/Asthriona/Yukiko/blob/master/commands/moderation/warns.js#L37

there should be 2 `==` and not 1 `=` as you are comparing

**Comment by Asthriona** [comment]
hi @FirezzzZ ! 
Indeed you right, I'll fix this soon, We are working to upgrade the bot to Discord.js v12 so it will be fixed at the same time.
Thanks again :)

**Comment by FirezTheGreat** [comment]
`let mutetime = "10m"` as you are assigning it and cannnot compare in a variable

**Comment by Heazher** [comment]
This issue is inactive for too long, I'm closing it now.
